process.env.BASE_URL = 'https://www.example.com'
process.env.API_URL = 'https://api.example.com'
process.env.AUTH_URL = 'https://auth.example.com'
process.env.PROJECT_KEY = 'project-key'
process.env.API_TOKEN = 'api-token'